site_name: MLRecruiters
site_url: https://fastapi.tiangolo.com/
site_author: Strategy-Tap PLC
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project – customizable,
  searchable, mobile-friendly, 40+ languages

repo_name: tiangolo/fastapi
repo_url: https://github.com/Strategy-Tap/MLRecruiters-BackEnd
edit_uri: ''

copyright: Copyright &copy; 2020 Mohamed Nesredin

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - tabs

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/novizi

nav:
  - Home: 'index.md'
  - Reference:
      - Manage: "reference/manage.md"


markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed


extra_css:
    - 'css/termynal.css'
    - 'css/custom.css'

extra_javascript:
    - 'https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js'
    - 'js/termynal.js'
    - 'js/custom.js'
